MGMT-10972 - E2E for Dualstack
openshift-assisted/openshift-assisted-ui pull request #4
Opened 2022-07-08 10:26 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-10972

2022-07-11 13:52 UTC, celdrake requested changes

2022-07-11 13:52 UTC, celdrake commented on packages/integration-tests/src/integration/dualstack/2-networking.spec.js
> +    if (utils.isAIAPIMocked) {
I think we don't need `isAIAPIMocked` anymore, since it was when I assumed we would have both Integration and e2e tests. Besides, it's a function so this would always evaluate to true.

But we can remove this from all tests and leave only the mocked part.

2022-07-11 13:52 UTC, celdrake commented on packages/integration-tests/src/integration/dualstack/2-networking.spec.js
> +    networkingPage.getStackTypeSingleStack().should('be.enabled').and('be.checked');
The first assertion is duplicate.

2022-07-11 13:52 UTC, celdrake commented on packages/integration-tests/src/integration/dualstack/2-networking.spec.js
> +      utils.setTransformSignal('dual-stack');
I like the idea of a `transformSignal`, as I think for some cases we'd need something like this.
But I still think they should always be done as part of some changes done by the user, and we should validate that the request the UI sends is what we expect.

Please check how @DanielleChason did it, something similar is needed here too.
https://github.com/openshift-assisted/openshift-assisted-ui/pull/6/files#diff-e7acf51a2a3ae9860f369c31a219f461c957c4ce6c7b1c0fb0393059a959bc63R95

After we validate that the request that UI sent had all the expected data, then we can return a new mocked response with those same details.

2022-07-12 08:11 UTC, jgyselov commented on packages/integration-tests/src/integration/dualstack/2-networking.spec.js
> +    if (utils.isAIAPIMocked) {
Removed from the codebase.

2022-07-12 11:06 UTC, jgyselov commented on packages/integration-tests/src/integration/dualstack/2-networking.spec.js
> +      utils.setTransformSignal('dual-stack');
I added validation of the request body similar to Danielle's inside of the `transformFixture` function that runs before we return the response. But I don't know if I can think of a better way to do this than setting the `transformSignal` before the request is intercepted.

2022-07-12 12:28 UTC, celdrake approved these changes
Looks good :)

2022-07-12 14:11 UTC, merged